# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(450, 320)
        Form.setMinimumSize(QtCore.QSize(450, 320))
        Form.setMaximumSize(QtCore.QSize(450, 320))
        Form.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.contentBox = QtWidgets.QWidget(Form)
        self.contentBox.setStyleSheet("#contentTop{\n"
"border: none;\n"
"border-bottom: 2px solid grey;\n"
"}\n"
"\n"
"#name, #group, #resistance{\n"
"background-color: white;\n"
"border: 1px solid black;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"#submit{\n"
"padding: 5px 10px;\n"
"}")
        self.contentBox.setObjectName("contentBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.contentBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.contentTop = QtWidgets.QFrame(self.contentBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contentTop.sizePolicy().hasHeightForWidth())
        self.contentTop.setSizePolicy(sizePolicy)
        self.contentTop.setStyleSheet("")
        self.contentTop.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentTop.setObjectName("contentTop")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.contentTop)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.contentTop)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.contentTop)
        self.contentBottom = QtWidgets.QFrame(self.contentBox)
        self.contentBottom.setObjectName("contentBottom")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.contentBottom)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.loginContent = QtWidgets.QFrame(self.contentBottom)
        self.loginContent.setObjectName("loginContent")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.loginContent)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.name = QtWidgets.QFrame(self.loginContent)
        self.name.setObjectName("name")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.name)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.name)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.name)
        self.lineEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout_5.addWidget(self.name)
        self.group = QtWidgets.QFrame(self.loginContent)
        self.group.setObjectName("group")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.group)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.group)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.group)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.verticalLayout_5.addWidget(self.group)
        self.resistance = QtWidgets.QFrame(self.loginContent)
        self.resistance.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.resistance.setFrameShadow(QtWidgets.QFrame.Raised)
        self.resistance.setObjectName("resistance")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.resistance)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.resistance)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.comboBox = QtWidgets.QComboBox(self.resistance)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox)
        self.verticalLayout_5.addWidget(self.resistance)
        self.verticalLayout_4.addWidget(self.loginContent)
        self.submit = QtWidgets.QPushButton(self.contentBottom)
        self.submit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.submit.setObjectName("submit")
        self.verticalLayout_4.addWidget(self.submit)
        self.verticalLayout_2.addWidget(self.contentBottom)
        self.verticalLayout.addWidget(self.contentBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Ввод данных"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\">Лабараторная работа №24</p><p align=\"center\">&quot;Определение коэффицента самоиндукции катушки&quot;</p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\">Введте ФИО</p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\">Введите группу</p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p align=\"center\">Выберите сопротивление</p></body></html>"))
        self.comboBox.setItemText(0, _translate("Form", "20 Ом"))
        self.submit.setText(_translate("Form", "Приступить к выполнению работы"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
